name: Test
on: [push]
 # jobs запускаются параллельно, если не указана последовательность
jobs:
  # Название job вы можете назвать как угодно
 test:
  # Операционная система в виртуальной машине, в которой запускаются процессы
    runs-on: ubuntu-latest
    # Шаги
    steps:

       - uses: actions/checkout@v3
       - uses: actions/setup-java@v3
         with:
              distribution: 'zulu'
              java-version: '17'
       - uses: Xotabu4/selenoid-github-action@v2
        # Пример однолинейного простого скрипта shell
       - run: gradle wrapper
       - run: chmod +x ./gradlew
       - run: ./gradlew clean test  -Dselenide.remote=http://localhost:4444/wd/hub


       - uses: actions/checkout@v2
         if: always()
         continue-on-error: true
         with:
           ref: gh-pages
           path: gh-pages


       -  uses: simple-elf/allure-report-action@master
          if: always()
          with:
             gh_pages: gh-pages
             allure_results: build/allure-results
             allure_report: allure-report
             allure_history: allure-history



       -  uses: peaceiris/actions-gh-pages@v2
          if: always()
         env:
           PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           PUBLISH_BRANCH: gh-pages
           PUBLISH_DIR: allure-history


