name: Test
on: [push]
 # jobs запускаются параллельно, если не указана последовательность
jobs:
  # Название job вы можете назвать как угодно
 test:
  # Операционная система в виртуальной машине, в которой запускаются процессы
    runs-on: ubuntu-latest
    # Шаги
    steps:
      # Actions от github: проверяет репозиторий, гит и т.д.
       - uses: actions/checkout@v3
       - uses: actions/setup-java@v3
         with:
              distribution: 'zulu'
              java-version: '17'
       - uses: Xotabu4/selenoid-github-action@v2
        # Пример однолинейного простого скрипта shell
       - run: gradle wrapper
       - run: chmod +x ./gradlew
       - run: ./gradlew clean test  -Dselenide.remote=http://localhost:4444/wd/hub

